### ISSUE TITLE
TabError in cp2k.py

### ISSUE THREAD

**Issue by geepradeep** [ltalirz/asetk#7]
`/redacted/.local/bin/cp2k-sumbias.py --cubes *WFN*.cube --levelsfile molly1.out --vmin -3.0 --vmax 3.0 --vstep 0.5 | tee sumbias.out`
`Traceback (most recent call last):`
`  File "/redacted/.local/bin/cp2k-sumbias.py", line 7, in <module>`
`    exec(compile(f.read(), __file__, 'exec'))`
`  File "/redacted/software/asetk/scripts/cp2k-sumbias.py", line 6, in <module>`
`    import asetk.format.cp2k as cp2k`
`  File "/redacted/software/asetk/asetk/format/cp2k.py", line 260`
`    A = np.genfromtxt(fname, skip_header=2)`
`                                          ^`
`TabError: inconsistent use of tabs and spaces in indentation`

The simple issue is fixed with
`autopep8 -i cp2k.py`
but I wanted to bring it to your notice. Thanks for the toolkit - very helpful by the way!

**Comment by ltalirz** [comment]
Hi @geepradeep , thanks for the report and the kind words, always happy to hear!

Would you mind making a small PR to fix this?

**Comment by ltalirz** [comment]
closed by bdb31934a5eb49d601e492fc98078d27f5dd2ebd
